FROM centos:7

WORKDIR /hicn-build
SHELL ["/bin/bash", "-c"]
RUM yum update -y
RUN yum install -y epel-release; yum clean all
RUN yum install -y git cmake make rpm-build devtoolset-7 pcre-devel libssl
