name: Docker Image CI arm64
on: [push]
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Run Buildx
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} \
                       -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker buildx build \
            --platform linux/arm64 \
            --output type=docker \
            --file Dockerfile -t icnteam/vswitch .
            