name: Docker Image CI
on: [push]
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --output "type=image,push=false" \
            --file Dockerfile -t icn-team/vswitch/core:latest .
      - name: Publish to DockerHub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: icnteam/vswitch/core:latest
          username: icnteam
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: icn-team/vswitch/core:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
     
