name: Docker Image CI amd64
on: [push]
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --output type=docker \
            --file Dockerfile -t icnteam/vswitch .
      - name: Publish to DockerHub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: icnteam/vswitch:latest 
          run: docker tag icnteam/vswitch:amd64 icnteam/vswitch
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

